trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'components/*'
      - 'main/*'
      - 'test/*'

pool:
  name: default
  # This project must be built on a machine
  # with ESP-IDF installed.
  demands:
  - ESP-IDF -equals True

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: |
      cd "$(Build.Repository.LocalPath)"
      
      &"C:\espidfsources\export.ps1"
      &python.exe "C:\espidfsources\tools\idf.py" "set-target" "esp32"
      &python.exe "C:\espidfsources\tools\idf.py" "build"