#ifndef __NEXTION_CONFIG__
#define __NEXTION_CONFIG__

#ifndef CONFIG_NEX_RESP_MSG_MAX_LENGTH
#define CONFIG_NEX_RESP_MSG_MAX_LENGTH (NEX_DVC_SERIAL_ACK_LENGTH + 100) // 1 text response with 100 chars.
#endif

#ifndef CONFIG_NEX_UART_BUFFER_MULT
#define CONFIG_NEX_UART_BUFFER_MULT 5
#endif

#ifndef CONFIG_NEX_UART_QUEUE_SIZE
#define CONFIG_NEX_UART_QUEUE_SIZE 10
#endif

#ifndef CONFIG_NEX_RESP_WAIT_TIME_MS
#define CONFIG_NEX_RESP_WAIT_TIME_MS 1000
#endif

#ifndef CONFIG_NEX_EVENT_QUEUE_WAIT_TIME_MS
#define CONFIG_NEX_EVENT_QUEUE_WAIT_TIME_MS 50
#endif

#endif //__NEXTION_C__