name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'components/**'
      - 'main/**'
      - 'test/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  esp_docker_tag: v5.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Pull ESP-IDF Image
      shell: pwsh
      run: docker pull espressif/idf:${{env.esp_docker_tag}}

    - name: Build with Sonar
      shell: pwsh
      run: docker run --rm -e LC_ALL='C.UTF-8' --env SONAR_ORGANIZATION_NAME=${{secrets.SONARCLOUD_ORGANIZATION}} --env SONAR_ORGANIZATION_TOKEN=${{secrets.SONARCLOUD_TOKEN}} -v ${{github.workspace}}:/project -w /project espressif/idf:${{env.esp_docker_tag}} bash .github/scripts/build-with-sonar.sh

    - name: Publish Binaries
      uses: actions/upload-artifact@v3.1.2
      with:
        name: binary
        path: ${{github.workspace}}/build/*.bin
        if-no-files-found: error
        retention-days: 1

    - name: Build Test
      shell: pwsh
      run: docker run --rm -e LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project espressif/idf:${{env.esp_docker_tag}} idf.py -C ./test build
